# Generated by Django 3.1.1 on 2021-03-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metroevent', '0006_auto_20210325_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='metroevent.event'),
        ),
    ]
