# Generated by Django 3.1.1 on 2021-03-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactno', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
                ('is_organizer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('organizers', models.ManyToManyField(related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='joined_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
