# Generated by Django 3.1.1 on 2021-03-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='User',
        ),
    ]
